{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "33001fd4-bf96-49c3-b203-2c7b412398b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-11 19:25:33.146 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.801 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-03-11 19:25:33.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.810 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.811 Session state does not function when running a script without `streamlit run`\n",
      "2026-03-11 19:25:33.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.842 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-11 19:25:33.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import joblib\n",
    "\n",
    "# Load your trained model\n",
    "model = joblib.load(\"fatigue_model.pkl\")\n",
    "\n",
    "# Map model outputs to activity\n",
    "activity_map = {0: \"Resting\", 1: \"Walking\", 2: \"Running\"}\n",
    "\n",
    "# App title\n",
    "st.title(\"Athlete Fatigue & Stress Monitoring System\")\n",
    "st.write(\"Enter the athlete's readings below:\")\n",
    "\n",
    "# User inputs\n",
    "heart_rate = st.number_input(\"Heart Rate (bpm)\")\n",
    "temperature = st.number_input(\"Body Temperature (°C)\")\n",
    "oxygen = st.number_input(\"Blood Oxygen (%)\")\n",
    "steps = st.number_input(\"Step Count\")\n",
    "\n",
    "# Predict button\n",
    "if st.button(\"Check Status\"):\n",
    "\n",
    "    # Prepare sample for prediction\n",
    "    sample = [[heart_rate, temperature, oxygen, steps]]\n",
    "    prediction = model.predict(sample)\n",
    "    activity = activity_map[prediction[0]]\n",
    "\n",
    "    # Display activity\n",
    "    st.success(f\"Predicted Activity: {activity}\")\n",
    "\n",
    "    # Add fatigue/stress alerts\n",
    "    if heart_rate > 120 and steps > 3000:\n",
    "        st.warning(\"⚠️ High fatigue risk detected! Athlete may be exhausted.\")\n",
    "    elif heart_rate > 100 and steps > 2000:\n",
    "        st.warning(\"⚠️ Moderate fatigue risk. Athlete may be stressed.\")\n",
    "    else:\n",
    "        st.info(\"Athlete condition appears normal.\")\n",
    "\n",
    "    # Optional: check temperature and oxygen\n",
    "    if temperature > 37.5:\n",
    "        st.warning(\"⚠️ Elevated body temperature detected. Check for stress or illness.\")\n",
    "    if oxygen < 95:\n",
    "        st.warning(\"⚠️ Low blood oxygen. Monitor athlete closely.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9edc8a2-167f-41b9-aac2-01d233352896",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
